//! Backup, restore, and export commands

use crate::backup::{ExportSummary, ImportPreview, ImportSummary};
use crate::error::AppError;
use crate::AppState;
use tauri::State;
use tauri_plugin_dialog::DialogExt;

// ============================================================================
// Export Commands
// ============================================================================

/// Export format enum
#[derive(serde::Deserialize, Clone, Copy)]
pub enum ExportFormat {
    Markdown,
    PlainText,
    Html,
}

impl ExportFormat {
    fn extension(&self) -> &str {
        match self {
            Self::Markdown => "md",
            Self::PlainText => "txt",
            Self::Html => "html",
        }
    }

    fn filter_name(&self) -> &str {
        match self {
            Self::Markdown => "Markdown",
            Self::PlainText => "Plain Text",
            Self::Html => "HTML",
        }
    }

    fn format_content(&self, response_text: &str) -> String {
        match self {
            Self::Markdown => format!(
                "# Response\n\n{}\n\n---\n*Generated by AssistSupport*",
                response_text
            ),
            Self::PlainText => response_text.to_string(),
            Self::Html => {
                // Convert newlines to <br> and wrap in basic HTML
                let escaped = response_text
                    .replace('&', "&amp;")
                    .replace('<', "&lt;")
                    .replace('>', "&gt;")
                    .replace('\n', "<br>\n");
                format!(
                    "<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\">\n  <title>Response</title>\n  <style>\n    body {{ font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; }}\n  </style>\n</head>\n<body>\n  <h1>Response</h1>\n  <div>{}</div>\n  <hr>\n  <p><em>Generated by AssistSupport</em></p>\n</body>\n</html>",
                    escaped
                )
            }
        }
    }
}

/// Map a `crate::backup` error to AppError, preserving the detail for logs.
fn backup_err(op: &str, e: impl std::fmt::Display) -> AppError {
    AppError::new(
        crate::error::ErrorCode::INTERNAL_ERROR,
        format!("Backup {} failed", op),
        crate::error::ErrorCategory::Internal,
    )
    .with_detail(e.to_string())
}

/// Export a draft response to a file
#[tauri::command]
pub async fn export_draft(
    app: tauri::AppHandle,
    response_text: String,
    format: ExportFormat,
) -> Result<bool, AppError> {
    let content = format.format_content(&response_text);
    let default_filename = format!("response.{}", format.extension());

    // Build file dialog
    let file_handle = app
        .dialog()
        .file()
        .set_file_name(&default_filename)
        .add_filter(format.filter_name(), &[format.extension()])
        .blocking_save_file();

    match file_handle {
        Some(path) => {
            let file_path = path
                .as_path()
                .ok_or_else(|| AppError::invalid_path("Invalid file path"))?;

            std::fs::write(file_path, content).map_err(AppError::from)?;

            Ok(true)
        }
        None => {
            // User cancelled — return Ok(false) to preserve the existing
            // "cancelled is not an error" semantic for this command.
            Ok(false)
        }
    }
}

// ============================================================================
// Backup/Restore Commands
// ============================================================================

/// Export all app data to a backup file (optionally encrypted with password)
#[tauri::command]
pub async fn export_backup(
    app: tauri::AppHandle,
    state: State<'_, AppState>,
    password: Option<String>,
) -> Result<ExportSummary, AppError> {
    let db_lock = state.db.lock().map_err(|_| AppError::db_lock_failed())?;
    let db = db_lock.as_ref().ok_or_else(AppError::db_not_initialized)?;

    // Determine file extension based on encryption
    let (filename, filter_name, extensions) = if password.is_some() {
        ("assistsupport-backup.enc", "Encrypted Backup", &["enc"][..])
    } else {
        ("assistsupport-backup.zip", "ZIP Archive", &["zip"][..])
    };

    // Show save file dialog
    let file_handle = app
        .dialog()
        .file()
        .set_file_name(filename)
        .add_filter(filter_name, extensions)
        .blocking_save_file();

    match file_handle {
        Some(path) => {
            let file_path = path
                .as_path()
                .ok_or_else(|| AppError::invalid_path("Invalid file path"))?;

            crate::backup::export_backup(db, file_path, password.as_deref())
                .map_err(|e| backup_err("export", e))
        }
        None => Err(AppError::cancelled()),
    }
}

/// Preview what will be imported from a backup file (with optional password for encrypted backups)
#[tauri::command]
pub async fn preview_backup_import(
    app: tauri::AppHandle,
    password: Option<String>,
) -> Result<ImportPreview, AppError> {
    // Show open file dialog (accept both ZIP and encrypted backups)
    let file_handle = app
        .dialog()
        .file()
        .add_filter("Backup Files", &["zip", "enc"])
        .add_filter("ZIP Archive", &["zip"])
        .add_filter("Encrypted Backup", &["enc"])
        .blocking_pick_file();

    match file_handle {
        Some(path) => {
            let file_path = path
                .as_path()
                .ok_or_else(|| AppError::invalid_path("Invalid file path"))?;

            crate::backup::preview_import(file_path, password.as_deref())
                .map_err(|e| backup_err("preview", e))
        }
        None => Err(AppError::cancelled()),
    }
}

/// Import data from a backup file (with optional password for encrypted backups)
#[tauri::command]
pub async fn import_backup(
    app: tauri::AppHandle,
    state: State<'_, AppState>,
    password: Option<String>,
) -> Result<ImportSummary, AppError> {
    // Show open file dialog (accept both ZIP and encrypted backups)
    let file_handle = app
        .dialog()
        .file()
        .add_filter("Backup Files", &["zip", "enc"])
        .add_filter("ZIP Archive", &["zip"])
        .add_filter("Encrypted Backup", &["enc"])
        .blocking_pick_file();

    match file_handle {
        Some(path) => {
            let file_path = path
                .as_path()
                .ok_or_else(|| AppError::invalid_path("Invalid file path"))?;

            {
                let db_lock = state.db.lock().map_err(|_| AppError::db_lock_failed())?;
                if let Some(db) = db_lock.as_ref() {
                    return crate::backup::import_backup(db, file_path, password.as_deref())
                        .map_err(|e| backup_err("import", e));
                }
            }

            // No live DB — fall back to the recovery-mode restore path.
            let restore_result = {
                let recovery_lock = state
                    .recovery
                    .lock()
                    .map_err(|_| AppError::lock_failed("recovery context"))?;
                let recovery = recovery_lock
                    .as_ref()
                    .ok_or_else(AppError::db_not_initialized)?;
                let db_path = recovery.db_path.as_ref().ok_or_else(|| {
                    AppError::invalid_format(
                        "Backup restore is not available for this recovery issue",
                    )
                })?;
                let master_key = recovery.master_key.as_ref().ok_or_else(|| {
                    AppError::invalid_format(
                        "Backup restore is not available for this recovery issue",
                    )
                })?;

                crate::backup::restore_backup_into_fresh_database(
                    db_path,
                    master_key,
                    file_path,
                    password.as_deref(),
                )
            };

            if restore_result.is_ok() {
                let mut recovery_lock = state
                    .recovery
                    .lock()
                    .map_err(|_| AppError::lock_failed("recovery context"))?;
                *recovery_lock = None;
            }

            restore_result.map_err(|e| backup_err("restore", e))
        }
        None => Err(AppError::cancelled()),
    }
}
