#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
mode="${1:-clean}"

delete_paths=(
  "node_modules"
  "src-tauri/target"
  "src-tauri/gen"
  "src-tauri/permissions/autogenerated"
  "search-api/venv"
  "search-api/.venv"
  ".venv"
  "dist"
  "build"
  "out"
  ".next"
  "coverage"
  ".pytest_cache"
  ".cache"
  "tmp"
  ".lighthouseci"
  ".perf-results"
  ".husky/_"
  "playwright-report"
  "blob-report"
  "test-results"
  ".hypothesis"
  "search-api/.hypothesis"
  "search-api/.pytest_cache"
  "search-api/__pycache__"
  "search-api/tests/__pycache__"
  "scripts/perf/db/__pycache__"
)

print_action() {
  local action="$1"
  local target="$2"
  printf '%s %s\n' "$action" "$target"
}

remove_path() {
  local target="$1"
  local full_path="$root_dir/$target"
  if [[ -e "$full_path" ]]; then
    print_action "remove" "$target"
    rm -rf "$full_path"
  fi
}

remove_ds_store() {
  while IFS= read -r path; do
    print_action "remove" "${path#"$root_dir/"}"
    rm -f "$path"
  done < <(find "$root_dir" -path "$root_dir/.git" -prune -o -name '.DS_Store' -type f -print)
}

case "$mode" in
  clean)
    for target in "${delete_paths[@]}"; do
      remove_path "$target"
    done
    remove_ds_store
    ;;
  --dry-run)
    for target in "${delete_paths[@]}"; do
      if [[ -e "$root_dir/$target" ]]; then
        print_action "would remove" "$target"
      fi
    done
    while IFS= read -r path; do
      print_action "would remove" "${path#"$root_dir/"}"
    done < <(find "$root_dir" -path "$root_dir/.git" -prune -o -name '.DS_Store' -type f -print)
    ;;
  *)
    echo "Usage: scripts/clean-local.sh [clean|--dry-run]"
    exit 1
    ;;
esac
